--- #YAML:1.0
name:                Proc-Daemon
version:             0.14
abstract:            ~
license:             perl
author:              
    - Earl Hood earl@earlhood.com, Detlef Pilzecker deti@cpan.org
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POSIX:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
